exams/urls.py
from django.urls import path, include
from rest_framework import routers

from . import api
from . import views

router = routers.DefaultRouter()
router.register(r'exam', api.ExamViewSet)
router.register(r'question', api.QuestionViewSet)


urlpatterns = (
    # urls for Django Rest Framework API
    path('api/v1/', include(router.urls)),
)

urlpatterns += (
    # urls for Exam
    path('exams/exam/', views.ExamListView.as_view(), name='exams_exam_list'),
    path('exams/exam/create/', views.ExamCreateView.as_view(),
         name='exams_exam_create'),
    path('exams/exam/detail/<int:pk>/',
         views.ExamDetailView.as_view(), name='exams_exam_detail'),
    path('exams/exam/update/<int:pk>/',
         views.ExamUpdateView.as_view(), name='exams_exam_update'),
)

urlpatterns += (
    # urls for Question
    path('exams/question/', views.QuestionListView.as_view(),
         name='exams_question_list'),
    path('exams/question/create/', views.QuestionCreateView.as_view(),
         name='exams_question_create'),
    path('exams/question/detail/<int:pk>/',
         views.QuestionDetailView.as_view(), name='exams_question_detail'),
    path('exams/question/update/<int:pk>/',
         views.QuestionUpdateView.as_view(), name='exams_question_update'),
)

urlpatterns += (
     # urls for Write Answer
     path('write_answers/',
          views.write_answers,
          name='write_answers'
          ),
     path('get_courses/',
          views.get_courses,
          name='get_courses'
          ),
     path('get_subjects/',
          views.get_subjects,
          name='get_subjects'
          ),
     path('get_exams/',
          views.get_exams,
          name='get_exams'
          ),
     path('write_answer/<str:exam_pk>/<str:question_pk>/',
          views.write_answer,
          name='write_answer'
          ),
     path('update_answer/',
          views.update_answer,
          name='update_answer'
          ),
     path('view_answers/',
          views.view_answers,
          name='view_answers'
          ),
     path('view_answers/<str:exam_id>/',
          views.view_question_paper,
          name='view_question_paper'
          ),
     path('view_answers/<str:exam_id>/<str:question_id>/',
          views.view_answer,
          name='view_answer'
          ),
     path('view_answers/<str:exam_id>/<str:question_id>/vote/',
          views.vote,
          name='vote'
          ),
     path('view_answers/<str:exam_id>/<str:question_id>/feedback/',
          views.answer_feedback,
          name='answer_feedback'
          ),
)

urlpatterns += (
    # urls for AnswerFeedback
    path('answerfeedback/',
         views.answer_feedback_list,
         name='exams_answerfeedback_list'
         ),
    path('answerfeedback/detail/<int:pk>/',
         views.answer_feedback_detail,
         name='exams_answerfeedback_detail'
         ),
    path('answerfeedback/update/<int:pk>/',
         views.answer_feedback_update,
         name='exams_answerfeedback_update'
         ),
)

university_dost/users/urls.py
from django.urls import path

from university_dost.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

exams/models.py
from django.urls import reverse
from config.settings.base import AUTH_USER_MODEL
from django.db import models
from universities.models import Subject
from config.utils import random_string_generator
from markdownx.models import MarkdownxField


class Exam(models.Model):

    # Choices
    MONTH_CHOICES = (
        ('january', 'January'),
        ('february', 'February'),
        ('march', 'March'),
        ('april', 'April'),
        ('may', 'May'),
        ('june', 'June'),
        ('july', 'July'),
        ('august', 'August'),
        ('september', 'September'),
        ('october', 'October'),
        ('november', 'November'),
        ('december', 'December')
    )
    TERM_CHOICES = (
        ('summer', 'Summer'),
        ('winter', 'Winter')
    )

    # Fields
    month = models.CharField(max_length=128, choices=MONTH_CHOICES)
    year = models.CharField(max_length=4)
    term = models.CharField(max_length=12, choices=TERM_CHOICES)
    date = models.DateField()
    total_time = models.CharField(max_length=12)
    total_marks = models.IntegerField()
    exam_code = models.CharField(max_length=128, blank=True, null=True)
    exam_complete = models.BooleanField(default=False)

    # Relationship Fields
    subject = models.ForeignKey(
        Subject, on_delete=models.CASCADE
    )

    class Meta:
        ordering = ('-pk',)

    def save(self, *args, **kwargs):
        if self.exam_code and len(self.exam_code.split('-')) > 3:
            self.exam_code = self.exam_code.split('-')[3]
        self.exam_code = '{}-{}'.format(
            self.subject.subject_code,
            random_string_generator(size=5)
            )
        qs_exists = Exam.objects.filter(exam_code=self.exam_code).exists()
        if qs_exists:
            self.exam_code = '{}-{}'.format(self.subject.subject_code,
                                            random_string_generator(size=5))
        super(Exam, self).save(*args, **kwargs)

    def __str__(self):
        return self.subject.name + " " + self.term + "-" + self.year

    def get_absolute_url(self):
        return reverse('exams_exam_detail', args=(self.pk,))

    def get_update_url(self):
        return reverse('exams_exam_update', args=(self.pk,))


class Question(models.Model):

    # Choices
    QUESTION_TYPE_CHOICES = (
        ('mcq', 'MCQ'),
        ('short_question', 'Short Question'),
        ('descriptive_question', 'Descriptive Question'),
    )

    # Fields
    question_code = models.CharField(max_length=128, blank=True, null=True)
    question_number = models.CharField(max_length=128)
    question_body = MarkdownxField()
    question_type = models.CharField(
        max_length=12, choices=QUESTION_TYPE_CHOICES)
    answer = MarkdownxField(blank=True, null=True)
    explanation = MarkdownxField(blank=True, null=True)
    marks = models.IntegerField()
    upvote = models.IntegerField(default=0)
    downvote = models.IntegerField(default=0)

    # Relationship Fields
    exam = models.ForeignKey(
        Exam, on_delete=models.CASCADE
    )
    author = models.ForeignKey(
        AUTH_USER_MODEL, blank=True, null=True, on_delete=models.SET_NULL
    )

    class Meta:
        ordering = ('-pk',)

    def save(self, *args, **kwargs):
        if len(self.question_code.split('-')) > 4:
            self.question_code = self.question_code.split('-')[4]
        self.question_code = '{}-{}'.format(
            self.exam.exam_code,
            self.question_code
            )
        super(Question, self).save(*args, **kwargs)

    def __str__(self):
        return (self.question_number +
                " | " + self.exam.term +
                "-" + self.exam.year
                )

    def get_absolute_url(self):
        return reverse('exams_question_detail', args=(self.pk,))

    def get_update_url(self):
        return reverse('exams_question_update', args=(self.pk,))


class AnswerFeedback(models.Model):

    # Choices
    FEEDBACK_TYPE_CHOICES = (
        ('wrong_answer', 'Wrong Answer'),
        ('improvement', 'Improvement'),
    )
    FEEDBACK_STATUS_CHOICES = (
        ('received', 'Received'),
        ('reviewing', 'Reviewing'),
        ('reviewed', 'Reviewed'),
        ('resolved', 'Resolved')
    )

    # Fields
    feedback_title = models.CharField(max_length=256, blank=True, null=True)
    feedback_body = models.TextField()
    feedback_type = models.CharField(
        max_length=128, choices=FEEDBACK_TYPE_CHOICES)
    feedback_status = models.CharField(
        max_length=128,
        choices=FEEDBACK_STATUS_CHOICES,
        default='received')
    user_email = models.EmailField(max_length=256, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # Relationship Fields
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE
    )
    user = models.ForeignKey(
        AUTH_USER_MODEL, blank=True, null=True, on_delete=models.SET_NULL
    )

    class Meta:
        ordering = ('-pk',)

    def __str__(self):
        return self.feedback_title

    def get_absolute_url(self):
        return reverse('exams_answerfeedback_detail', args=(self.pk,))

    def get_update_url(self):
        return reverse('exams_answerfeedback_update', args=(self.pk,))

university_dost/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

university_dost/users/forms.py
from django.contrib.auth import forms, get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

university_dost/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

university_dost/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

university_dost/templates/includes/_navbar.html
 {% load static i18n avatar_tags %}
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">University Dost</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            {% if request.user.is_authenticated %} {% if perms.exams.change_question %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'write_answers'  %}">{% trans "Write Answers" %}</a>
            </li>
            {% else %} {% endif %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'view_answers'  %}">{% trans "View Answers" %}</a>
            </li>
            
            {% else %}
            {% endif %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if request.user.is_authenticated %}

            <li class="dropdown">
                <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown"><i class="fa fa-lg fa-user-circle-o" aria-hidden="true"></i> &nbsp;{% trans "Profile" %} <b class="caret"></b></a>
                <ul class="dropdown-menu dropdown-menu-right" style="padding: 15px;min-width: 250px;">
                  <li>
                    <div class="navbar-login">
                        <div class="row">
                            <div class="col-lg-4">
                                <p class="text-center">
                                  <img src="{% avatar_url user 75 %}" class="rounded img-fluid" id="user_avatar" alt="{{user.first_name}} {{user.last_name}}">
                                </p>
                            </div>
                            <div class="col-lg-8">
                                <p class="text-left"><strong>{{user.first_name}} {{user.last_name}}</strong></p>
                                <p class="text-left small">{{user.email}}</p>
                                <p class="text-left">
                                    <a href="{% url 'users:detail' request.user.username %}" class="btn btn-primary btn-block btn-sm">Update Profile</a>
                                </p>
                            </div>
                        </div>
                    </div>
                </li>
                <li class="divider"></li>
                <li>
                    <div class="navbar-login navbar-login-session">
                        <div class="row">
                            <div class="col-lg-12">
                                <p>
                                    <a href="{% url 'account_logout' %}" class="btn btn-danger btn-block">Sign Out</a>
                                </p>
                            </div>
                        </div>
                    </div>
                </li>
                   
                </ul>
             </li>
            
             {% else %}
            <li><a class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a></li>
            <li class="dropdown">
               <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">{% trans "Sign In" %} <b class="caret"></b></a>
               <ul class="dropdown-menu dropdown-menu-right" style="padding: 15px;min-width: 250px;">
                  <li>
                     <div class="row">
                        <div class="col-md-12">
                           <form class="form login" role="form" method="post" action="{% url 'account_login' %}" accept-charset="UTF-8" id="login-nav">
                            {% csrf_token %}  
                            <div class="form-group">
                                 <label class="sr-only" for="exampleInputEmail2">{% trans "Email address" %}</label>
                                 <input type="text" name="login" placeholder="{% trans 'Username or Email address' %}" autofocus="autofocus" class="form-control" required id="id_login" />
                              </div>
                              <div class="form-group">
                                 <label class="sr-only" for="exampleInputPassword2">{% trans "Password" %}</label>
                                 <input type="password" name="password" placeholder="{% trans 'Password' %}" class="form-control" required id="id_password" />
                              </div>
                              <div class="checkbox">
                                 <label>
                                 <input type="checkbox" name="remember"id="id_remember" /> {% trans 'Remember Me' %}
                                 </label>
                              </div>
                              <div class="form-group">
                                 <a class="button secondaryAction" href="{% url 'account_reset_password' %}">{% trans "Forgot Password?" %}</a>
                              </div>
                              <div class="form-group">
                                 <button type="submit" class="btn btn-success btn-block">{% trans 'Sign In' %}</button>
                              </div>
                           </form>
                        </div>
                     </div>
                  </li>
                  <li>
                     <a href="/accounts/google/login/?process=login" class="btn btn-block btn-google">
                        <span class="fa fa-google"></span> Sign in with Google
                     </a>
                  </li>
               </ul>
            </li>
            
            {% endif %}
         </ul>
        </div>
      </nav>