exams/urls.py
from django.urls import path, include
from rest_framework import routers

from . import api
from . import views

router = routers.DefaultRouter()
router.register(r'exam', api.ExamViewSet)
router.register(r'question', api.QuestionViewSet)


urlpatterns = (
    # urls for Django Rest Framework API
    path('api/v1/', include(router.urls)),
)

urlpatterns += (
    # urls for Exam
    path('exams/exam/', views.ExamListView.as_view(), name='exams_exam_list'),
    path('exams/exam/create/', views.ExamCreateView.as_view(),
         name='exams_exam_create'),
    path('exams/exam/detail/<int:pk>/',
         views.ExamDetailView.as_view(), name='exams_exam_detail'),
    path('exams/exam/update/<int:pk>/',
         views.ExamUpdateView.as_view(), name='exams_exam_update'),
)

urlpatterns += (
    # urls for Question
    path('exams/question/', views.QuestionListView.as_view(),
         name='exams_question_list'),
    path('exams/question/create/', views.QuestionCreateView.as_view(),
         name='exams_question_create'),
    path('exams/question/detail/<int:pk>/',
         views.QuestionDetailView.as_view(), name='exams_question_detail'),
    path('exams/question/update/<int:pk>/',
         views.QuestionUpdateView.as_view(), name='exams_question_update'),
)

urlpatterns += (
     # urls for Write Answer
     path('write_answers/',
          views.write_answers,
          name='write_answers'
          ),
     path('get_courses/',
          views.get_courses,
          name='get_courses'
          ),
     path('get_subjects/',
          views.get_subjects,
          name='get_subjects'
          ),
     path('get_exams/',
          views.get_exams,
          name='get_exams'
          ),
     path('write_answer/<str:exam_pk>/<str:question_pk>/',
          views.write_answer,
          name='write_answer'
          ),
     path('update_answer/',
          views.update_answer,
          name='update_answer'
          ),
     path('view_answers/',
          views.view_answers,
          name='view_answers'
          ),
     path('view_answers/<str:exam_id>/',
          views.view_question_paper,
          name='view_question_paper'
          ),
     path('view_answers/<str:exam_id>/<str:question_id>/',
          views.view_answer,
          name='view_answer'
          ),
     path('view_answers/<str:exam_id>/<str:question_id>/vote/',
          views.vote,
          name='vote'
          ),
     path('view_answers/<str:exam_id>/<str:question_id>/feedback/',
          views.answer_feedback,
          name='answer_feedback'
          ),
)

urlpatterns += (
    # urls for AnswerFeedback
    path('answerfeedback/',
         views.answer_feedback_list,
         name='exams_answerfeedback_list'
         ),
    path('answerfeedback/detail/<int:pk>/',
         views.answer_feedback_detail,
         name='exams_answerfeedback_detail'
         ),
    path('answerfeedback/update/<int:pk>/',
         views.answer_feedback_update,
         name='exams_answerfeedback_update'
         ),
)

exams/models.py
from django.urls import reverse
from config.settings.base import AUTH_USER_MODEL
from django.db import models
from universities.models import Subject
from config.utils import random_string_generator
from markdownx.models import MarkdownxField


class Exam(models.Model):

    # Choices
    MONTH_CHOICES = (
        ('january', 'January'),
        ('february', 'February'),
        ('march', 'March'),
        ('april', 'April'),
        ('may', 'May'),
        ('june', 'June'),
        ('july', 'July'),
        ('august', 'August'),
        ('september', 'September'),
        ('october', 'October'),
        ('november', 'November'),
        ('december', 'December')
    )
    TERM_CHOICES = (
        ('summer', 'Summer'),
        ('winter', 'Winter')
    )

    # Fields
    month = models.CharField(max_length=128, choices=MONTH_CHOICES)
    year = models.CharField(max_length=4)
    term = models.CharField(max_length=12, choices=TERM_CHOICES)
    date = models.DateField()
    total_time = models.CharField(max_length=12)
    total_marks = models.IntegerField()
    exam_code = models.CharField(max_length=128, blank=True, null=True)
    exam_complete = models.BooleanField(default=False)

    # Relationship Fields
    subject = models.ForeignKey(
        Subject, on_delete=models.CASCADE
    )

    class Meta:
        ordering = ('-pk',)

    def save(self, *args, **kwargs):
        if self.exam_code and len(self.exam_code.split('-')) > 3:
            self.exam_code = self.exam_code.split('-')[3]
        self.exam_code = '{}-{}'.format(
            self.subject.subject_code,
            random_string_generator(size=5)
            )
        qs_exists = Exam.objects.filter(exam_code=self.exam_code).exists()
        if qs_exists:
            self.exam_code = '{}-{}'.format(self.subject.subject_code,
                                            random_string_generator(size=5))
        super(Exam, self).save(*args, **kwargs)

    def __str__(self):
        return self.subject.name + " " + self.term + "-" + self.year

    def get_absolute_url(self):
        return reverse('exams_exam_detail', args=(self.pk,))

    def get_update_url(self):
        return reverse('exams_exam_update', args=(self.pk,))


class Question(models.Model):

    # Choices
    QUESTION_TYPE_CHOICES = (
        ('mcq', 'MCQ'),
        ('short_question', 'Short Question'),
        ('descriptive_question', 'Descriptive Question'),
    )

    # Fields
    question_code = models.CharField(max_length=128, blank=True, null=True)
    question_number = models.CharField(max_length=128)
    question_body = MarkdownxField()
    question_type = models.CharField(
        max_length=12, choices=QUESTION_TYPE_CHOICES)
    answer = MarkdownxField(blank=True, null=True)
    explanation = MarkdownxField(blank=True, null=True)
    marks = models.IntegerField()
    upvote = models.IntegerField(default=0)
    downvote = models.IntegerField(default=0)

    # Relationship Fields
    exam = models.ForeignKey(
        Exam, on_delete=models.CASCADE
    )
    author = models.ForeignKey(
        AUTH_USER_MODEL, blank=True, null=True, on_delete=models.SET_NULL
    )

    class Meta:
        ordering = ('-pk',)

    def save(self, *args, **kwargs):
        if len(self.question_code.split('-')) > 4:
            self.question_code = self.question_code.split('-')[4]
        self.question_code = '{}-{}'.format(
            self.exam.exam_code,
            self.question_code
            )
        super(Question, self).save(*args, **kwargs)

    def __str__(self):
        return (self.question_number +
                " | " + self.exam.term +
                "-" + self.exam.year
                )

    def get_absolute_url(self):
        return reverse('exams_question_detail', args=(self.pk,))

    def get_update_url(self):
        return reverse('exams_question_update', args=(self.pk,))


class AnswerFeedback(models.Model):

    # Choices
    FEEDBACK_TYPE_CHOICES = (
        ('wrong_answer', 'Wrong Answer'),
        ('improvement', 'Improvement'),
    )
    FEEDBACK_STATUS_CHOICES = (
        ('received', 'Received'),
        ('reviewing', 'Reviewing'),
        ('reviewed', 'Reviewed'),
        ('resolved', 'Resolved')
    )

    # Fields
    feedback_title = models.CharField(max_length=256, blank=True, null=True)
    feedback_body = models.TextField()
    feedback_type = models.CharField(
        max_length=128, choices=FEEDBACK_TYPE_CHOICES)
    feedback_status = models.CharField(
        max_length=128,
        choices=FEEDBACK_STATUS_CHOICES,
        default='received')
    user_email = models.EmailField(max_length=256, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # Relationship Fields
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE
    )
    user = models.ForeignKey(
        AUTH_USER_MODEL, blank=True, null=True, on_delete=models.SET_NULL
    )

    class Meta:
        ordering = ('-pk',)

    def __str__(self):
        return self.feedback_title

    def get_absolute_url(self):
        return reverse('exams_answerfeedback_detail', args=(self.pk,))

    def get_update_url(self):
        return reverse('exams_answerfeedback_update', args=(self.pk,))

universities/models.py
from django.urls import reverse
from django.db import models
from django.db.models.signals import pre_save
from config.utils import (upload_university_logo_path,
                          upload_university_cover_path,
                          upload_course_cover_path,
                          upload_subject_cover_path,
                          unique_slug_generator,)


class University(models.Model):

    # Fields
    name = models.CharField(max_length=128)
    university_code = models.CharField(max_length=8)
    description = models.TextField()
    founded = models.DateField()
    address = models.TextField()
    phone = models.CharField(max_length=20)
    logo = models.ImageField(upload_to=upload_university_logo_path,
                             null=True, blank=True)
    cover = models.ImageField(
        upload_to=upload_university_cover_path, null=True, blank=True)

    class Meta:
        ordering = ('-pk',)
        verbose_name_plural = "universities"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('universities_university_detail', args=(self.pk,))

    def get_update_url(self):
        return reverse('universities_university_update', args=(self.pk,))


class Course(models.Model):

    # Choices
    COURSE_TYPE_CHOICES = (
        ('full-time', 'Full-Time'),
        ('part-time', 'Part-Time'),
    )
    DEGREE_TYPE_CHOICES = (
        ('be', 'Bachelor of Engineering'),
        ('btech', 'Bachelor of Technology'),
    )

    # Fields
    name = models.CharField(max_length=128)
    course_type = models.CharField(max_length=12, choices=COURSE_TYPE_CHOICES)
    degree_type = models.CharField(max_length=32, choices=DEGREE_TYPE_CHOICES)
    years = models.IntegerField()
    description = models.TextField()
    course_code = models.CharField(max_length=128)
    slug = models.SlugField(blank=True, unique=True)
    cover = models.ImageField(upload_to=upload_course_cover_path,
                              null=True, blank=True)

    # Relationship Fields
    university = models.ForeignKey(
        University,
        on_delete=models.CASCADE
    )

    class Meta:
        ordering = ('-pk',)

    def save(self, *args, **kwargs):
        if len(self.course_code.split('-')) > 1:
            self.course_code = self.course_code.split('-')[1]
        self.course_code = '{}-{}'.format(
            self.university.university_code,
            self.course_code
            )
        super(Course, self).save(*args, **kwargs)

    def __str__(self):
        return self.name+"-"+self.university.university_code

    def get_absolute_url(self):
        return reverse('universities_course_detail', args=(self.slug,))

    def get_update_url(self):
        return reverse('universities_course_update', args=(self.slug,))


def course_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(course_pre_save_receiver, sender=Course)


class Subject(models.Model):

    # Fields
    name = models.CharField(max_length=128)
    semester = models.IntegerField(default=2)  # remove default in production
    year = models.IntegerField()
    subject_code = models.CharField(max_length=128, blank=True, null=True)
    slug = models.SlugField(blank=True, unique=True)
    cover = models.ImageField(upload_to=upload_subject_cover_path,
                              null=True, blank=True)

    # Relationship Fields
    course = models.ForeignKey(
        Course,
        on_delete=models.CASCADE
    )

    class Meta:
        ordering = ('-pk',)

    def save(self, *args, **kwargs):
        if len(self.subject_code.split('-')) > 2:
            self.subject_code = self.subject_code.split('-')[2]
        self.subject_code = '{}-{}'.format(
            self.course.course_code,
            self.subject_code
            )
        super(Subject, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('universities_subject_detail', args=(self.slug,))

    def get_update_url(self):
        return reverse('universities_subject_update', args=(self.slug,))


def subject_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(subject_pre_save_receiver, sender=Subject)

exams/views/answer_feedback_methods.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from exams.models import Question, AnswerFeedback
from django.contrib import messages


# we need feedback, like everyone does
# and we listen to them or do we? (Vsauce)
@login_required
def answer_feedback(request, exam_id, question_id):
    if request.is_ajax():
        feedback = AnswerFeedback(
            user=request.user,
            question=Question.objects.get(id=question_id),
            user_email=request.user.email,
            feedback_type=request.POST.get('feedback_type'),
            feedback_title=request.POST.get('feedback_title'),
            feedback_body=request.POST.get('feedback_body'),
        )
        feedback.save()
        return HttpResponse(status=200)
    else:
        return HttpResponse(status=404)


@login_required
def answer_feedback_list(request):
    """This function displays list of all feedbacks"""

    if request.user.has_perm('exams.change_answerfeedback'):
        feedbacks = AnswerFeedback.objects.all()
        context = {
            'feedbacks': feedbacks
        }
        return render(request, 'exams/answerfeedback_list.html', context)
    else:
        return HttpResponse(status=403)


@login_required
def answer_feedback_detail(request, pk):
    """This function displays detail of a feedback"""

    if request.user.has_perm('exams.change_answerfeedback'):
        feedback = AnswerFeedback.objects.get(pk=pk)
        context = {
            'feedback': feedback
        }
        return render(request, 'exams/answerfeedback_detail.html', context)
    else:
        return HttpResponse(status=403)


@login_required
def answer_feedback_update(request, pk):
    """
    This function updates status of a feedback.
    The status fuction will be added soon.
    """

    if request.user.has_perm('exams.change_answerfeedback'):
        feedback = AnswerFeedback.objects.get(pk=pk)
        if request.method == 'POST':
            new_feedback_status = request.POST.get('feedback_status')
            feedback.feedback_status = new_feedback_status
            feedback.save()
            messages.success(
                request,
                'Feedback status has been updated successfully!'
                )
            context = {
                'feedback': feedback
            }
            return render(request, 'exams/answerfeedback_form.html', context)
        else:
            context = {
                'feedback': feedback
            }
            return render(request, 'exams/answerfeedback_form.html', context)
    else:
        return HttpResponse(status=403)

exams/views/get_courses.py
from django.http import JsonResponse, HttpResponse
from universities.models import Course


def get_courses(request):
    """Handler to return JsonResponse of available courses"""

    if request.is_ajax():
        university_id = request.POST.get('ui')
        if Course.objects.filter(university_id=university_id).exists():
            courses = Course.objects.filter(
                university_id=university_id).values('id', 'name')
        else:
            return JsonResponse({'no_result': True})
        courses_list = list()
        for course in courses:
            courses_list.append(course)
        return JsonResponse(courses_list, safe=False)
    else:
        return HttpResponse(status=404)

exams/views/get_exams.py
from django.http import JsonResponse, HttpResponse
from exams.models import Exam


def get_exams(request):
    """Handler to return JsonResponse of available exams"""
    if request.is_ajax():
        subject_id = request.POST.get('si')
        if Exam.objects.filter(subject_id=subject_id).exists():
            exams = Exam.objects.filter(
                subject_id=subject_id).values(
                    'id', 'month', 'year', 'exam_complete'
                    )
        else:
            return JsonResponse({'no_result': True})
        exam_list = list()
        for exam in exams:
            exam_list.append(exam)
        print(exam_list)
        return JsonResponse(exam_list, safe=False)
    else:
        return HttpResponse(status=404)

exams/views/get_subjects.py
from django.http import JsonResponse, HttpResponse
from universities.models import Subject


def get_subjects(request):
    """Handler to return JsonResponse of available subjects"""

    if request.is_ajax():
        course_id = request.POST.get('ci')
        if Subject.objects.filter(course_id=course_id).exists():
            subjects = Subject.objects.filter(
                course_id=course_id).values('id', 'name')
        else:
            return JsonResponse({'no_result': True})
        subjects_list = list()
        for subject in subjects:
            subjects_list.append(subject)
        return JsonResponse(subjects_list, safe=False)
    else:
        return HttpResponse(status=404)

exams/templates/exams/answerfeedback_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'exams_answerfeedback_list' %}"><i class="fa fa-home" aria-hidden="true"></i>
 &nbsp;&nbsp;Answer Feedbacks</a></p>
Title: <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ feedback.feedback_title }} <hr>
Body: <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ feedback.feedback_body }} <hr>
Type: <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ feedback.feedback_type }} <hr>
Created: <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ feedback.created }} <hr>
Last Updated: <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ feedback.updated }} <hr>
Question: <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<a href="/exams/view_answers/{{ feedback.question.exam.id }}/{{ feedback.question.id }}/">{{feedback.question.exam.subject.course.university}} > {{feedback.question.exam.subject.course.name}} > {{feedback.question.exam}} > {{feedback.question.question_number}}</a> <hr>

<a class="btn btn-primary" href="{{feedback.get_update_url}}">Update Status</a>

{% endblock %}

exams/templates/exams/view_answer.html
{% extends 'base.html' %}
{% load static i18n mathjax %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/exams/view_answer.css' %}">
<script src="https://cdnjs.cloudflare.com/ajax/libs/markdown-it/8.4.1/markdown-it.min.js" integrity="sha256-xPwMubQT+EaVMOh04FjyG49sNwJmmGYpnhWNh4osD5w=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/markdown-it-mathjax@2.0.0/markdown-it-mathjax.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/2.10.0/github-markdown.min.css" integrity="sha256-Ndk1ry+oGNFEaXt4kxlW/SYLbxat1O0DhaDd+lob0SY=" crossorigin="anonymous" />
{% mathjax_scripts %}
{% endblock css %}

{% block content %}

<h2 class="text-center">{{question.exam.subject.course.university}}</h2>
<h3 class="text-center">{{question.exam.subject.course.get_degree_type_display}} - {{question.exam.subject.course.name}} - {{question.exam.get_term_display}} {{question.exam.year}}</h3>
<p class="lead text-center">{{question.exam.subject}}</p>
<hr>

<div class="row">

    <div class="col-md-2">
        <div class="d-flex justify-content-center"><a class="btn btn-primary btn-block" href="{% url 'view_question_paper' question.exam.id %}">Go to Question Paper</a></div>

        <!-- This will show next/previous buttons -->
        <!-- Checks whether there is any prev_question -->
        {% if prev_question %}
        <div class="d-flex justify-content-center" style="padding: 10px"><a class="btn btn-primary btn-block" href="{% url 'view_answer' question.exam.id prev_question.id %}"><i class="fa fa-lg fa-caret-left" aria-hidden="true"></i><i class="fa fa-lg fa-caret-left" aria-hidden="true"></i> Previous</a></div>
        {% else %}
        {% endif %}

        <!-- Checks whether there is any next_question -->
        {% if next_question %}
        <div class="d-flex justify-content-center" style="padding: 10px"><a class="btn btn-primary btn-block" href="{% url 'view_answer' question.exam.id next_question.id %}">Next <i class="fa fa-lg fa-caret-right" aria-hidden="true"></i><i class="fa fa-lg fa-caret-right" aria-hidden="true"></i></a></div>
        {% else %}
        {% endif %}
    </div>

    <div class="col-md-10 "><!-- This will show question, answer and other stuff -->
        <ul class="list-group">

            <li class="list-group-item">
                <div class="row">
                    <div class="col-md-1">
                        <div id="question_number">{{question.question_number}}</div><hr class="only-mobile-hr">
                    </div>
                    <div class="col-md-10">
                        <div class="question_body_output"></div><hr class="only-mobile-hr">
                    </div>
                    <div class="col-md-1">
                        <div id="marks">{{question.marks}} mar{{ question.marks|pluralize:"k,ks" }}</div><br>
                    </div>
                </div>
            </li>

            <li class="list-group-item"><strong>Answer:</strong>  <br>
                <div class="answer_output"></div>
            </li>
            
            {% if  question.explanation%}
            <p id="explanation">{{question.explanation}}</p>
            <li class="list-group-item"><strong>Explanation:</strong>  <br>
                <div class="explanation_output"></div>
            </li>
            {% else %}
            {% endif %}
            <li class="list-group-item">
                <div class="float-right"id="author">
                    <strong>Author:</strong>  {{question.author.first_name}} {{question.author.last_name}}
                </div>
            </li>
            <br>

            <hr>

            <!-- main votig process starts from here-->
            <div class="vote">
                <!-- check if the user is in fact the author of this answer.
                If s/he is, come on, don't let them vote their answer.
                Instead, ask them to edit the answer.
                -->
                {% if question.author == request.user %}
                    <a href="{% url 'write_answer' question.exam.pk question.pk %}" class="btn btn-success">
                        <i class="fa fa-edit" aria-hidden="true"></i> Edit
                    </a>
                {% else %}

                <!-- Below 40% and the answer will be reviewed -->
                <p>{{vote_msg}}</p>

                {% if casted_vote %}
                    <!-- this dude has already voted. kudos to him/her-->
                    <!-- oh man, I am taking this equality game too far. -->
                    <div class="alert alert-success" role="alert">
                        Seems like you have already voted!
                    </div>
                {% else %}
                    <div class="vote_area row">
                        <div class="col-md-1 col-2">
                            <!-- Vote Button: Yes -->
                            <form action="./vote/" id="upvote" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="vote_type" value="upvote" />
                                <button class="btn btn-success" type="submit"> 
                                    <i class="fa fa-thumbs-o-up" aria-hidden="true"></i> Yes
                                </button>
                            </form>
                        </div>
                        <div class="col-md-1 col-2">
                            <!-- Vote Button: No -->
                            <form action="./vote/" id="downvote" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="vote_type" value="downvote" />
                                <button class="btn btn-danger" type="submit"> 
                                    <i class="fa fa-thumbs-o-down" aria-hidden="true"></i> No
                                </button>
                            </form>
                        </div>
                    </div>
                {% endif %}

                

                <hr>
                <p>Do you have any changes/suggestions for this answer?</p>

                <!-- this button will toggle a modal 
                see code for modal.
                it will be roaming around here.
                just find it.-->
                <button type="button" class="btn btn-success" data-toggle="modal" data-target="#answerFeedback">
                    <i class="far fa-lightbulb" aria-hidden="true"></i> Provide Feedback
                </button>
            </div>
            {% endif %}
            <div class="extra-space"></div>

            
        </ul>
    </div>

</div>

<p id="question_body">{{question.question_body}}</p>
<p id="answer">{{question.answer}}</p>

<!-- Answer Feedback Form Modal -->
<div class="modal fade" id="answerFeedback" tabindex="-1" role="dialog" aria-labelledby="answerFeedbackLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="answerFeedbackLabel">Answer Feedback Form</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <form id="answer_feedback" action="./feedback/" method="post">
            {% csrf_token %}
                <div class="modal-body">
                    <div class="form-group">
                        <label for="feedback_title">Title</label>
                        <input type="test" class="form-control" id="feedback_title" name="feedback_title" placeholder="Title...">
                    </div>
                    <div class="form-group">
                        <label for="feedback_type">Feedback Type</label>
                        <select class="form-control" id="feedback_type" name="feedback_type">
                            <option value="" selected disabled hidden>Choose here</option>
                            <option value="wrong_answer">Wrong Answer</option>
                            <option value="improvement">Improvement</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="feedback_body">Body</label>
                        <textarea class="form-control" id="feedback_body" name="feedback_body" rows="3" placeholder="What happened exactly?"></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>

        </div>
    </div>
</div>
    
{% endblock content %}

{% block javascript %}
<script src="{% static 'js/exams/view_answer.js' %}"></script>
{% endblock javascript %}

exams/templates/exams/view_question_paper.html
{% extends 'base.html' %}
{% load static i18n mathjax %}
{% block css %}
<link href="{% static 'css/exams/submit-result.css' %}" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/markdown-it/8.4.1/markdown-it.min.js" integrity="sha256-xPwMubQT+EaVMOh04FjyG49sNwJmmGYpnhWNh4osD5w=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/markdown-it-mathjax@2.0.0/markdown-it-mathjax.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/2.10.0/github-markdown.min.css" integrity="sha256-Ndk1ry+oGNFEaXt4kxlW/SYLbxat1O0DhaDd+lob0SY=" crossorigin="anonymous" />
{% mathjax_scripts %}
{% endblock css %}

{% block content %}
    <h2 class="text-center">{{university}}</h2>
    <h3 class="text-center">{{course.get_degree_type_display}} - {{course.name}} - {{exam.get_term_display}} {{exam.year}}</h3>
    <ul class="list-group">
        <p class="lead">Subject: {{subject}}</p>
        <hr>
        
        <div class="row text-center" style="margin-bottom: 40px; border: 0.2px dotted; border-bottom: 0px">
            <div class="col-md-1">
                <u>Q#</u>
            </div>
            <div class="col-md-10">
                <u>Question</u>
            </div>
            <div class="col-md-1">
                <u>Marks</u>
            </div>
        </div>

        {% for exam_question in exam_questions %}
        <div class="row" style="margin-bottom: 40px; border: 0.2px dotted;">
            <div class="col-md-1">
                <a href="{% url 'view_answer' exam.id exam_question.id %}">{{exam_question.question_number}}</a>
            </div>
            <div class="col-md-10 question_body_output">
            <p id="question_body">{{exam_question.question_body}}</p>
            </div>
            <div class="col-md-1">
                {{exam_question.marks}} M
            </div>
        </div>
        {% endfor %}
    </ul>
{% endblock content %}

{% block javascript %}
<script src="{% static 'js/exams/view_answer.js' %}"></script>
{% endblock javascript %}